"""Added enum values to some field

Revision ID: 881819a4acc9
Revises: 74e9c77a814b
Create Date: 2025-01-05 23:56:21.892559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '881819a4acc9'
down_revision: Union[str, None] = '74e9c77a814b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'origin',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('Overseas', 'Native', name='player_origin'),
               existing_nullable=False)
    op.alter_column('players', 'player_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('Batsman', 'Bowler', 'All Rounder', 'Wicket Keeper', name='player_type'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('admin', 'user', 'team', name='role'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'user', 'team', name='role'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('players', 'player_type',
               existing_type=sa.Enum('Batsman', 'Bowler', 'All Rounder', 'Wicket Keeper', name='player_type'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.alter_column('players', 'origin',
               existing_type=sa.Enum('Overseas', 'Native', name='player_origin'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
